export const SHOW_ADD_COMMENT_FORM = 'SHOW_ADD_COMMENT_FORM';
export const HIDE_ADD_COMMENT_FORM = 'HIDE_ADD_COMMENT_FORM';
export const SEND_COMMENT_REQUEST = 'SEND_COMMENT_REQUEST';
export const SEND_COMMENT_SUCCESS = 'SEND_COMMENT_SUCCESS';
export const SEND_COMMENT_FAILED = 'SEND_COMMENT_FAILED';