export const GET_AVAILABLE_JOINTS = 'GET_AVAILABLE_JOINTS';

export const LIGHT_A_JOINT = 'LIGHT_A_JOINT';
export const LIGHT_A_JOINT_SUCCESS = 'LIGHT_A_JOINT_SUCCESS';
export const LIGHT_A_JOINT_ERROR = 'LIGHT_A_JOINT_ERROR';